runtime: python27
api_version: 1
threadsafe: true
service: food-alert

handlers:
  - url: /static/(.+)
    static_files: static/\1
    upload: static/.*

  - url: /.*
    static_files: index.html
    upload: index.html
